apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy-cm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cm
  template:
    metadata:
      labels:
        app: redis-cm
    spec:
      containers:
        - name: redis-container-cm
          image: redis:alpine
          ports:
            - containerPort: 6379
